tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Pack, ship and run any application as a lightweight container
brew "docker", link: false
brew "git"
brew "htop"
brew "jq"
brew "openjdk"
brew "maven"
brew "nvm"
brew "python@3.9"
brew "watch"
brew "yarn"
brew "zsh"
cask "chrome-devtools"
cask "franz"
cask "google-chrome"
cask "intellij-idea"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
